<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-10-10T12:14:26 IST" name="Default suite" finished-at="2022-10-10T12:14:56 IST" duration-ms="29890">
    <groups>
    </groups>
    <test started-at="2022-10-10T12:14:26 IST" name="Default test" finished-at="2022-10-10T12:14:56 IST" duration-ms="29890">
      <class name="TestNG.login">
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:TestNG.login@2c1b194a]" started-at="2022-10-10T12:14:26 IST" name="beforeMethod" finished-at="2022-10-10T12:14:37 IST" duration-ms="11482" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="valid()[pri:1, instance:TestNG.login@2c1b194a]" started-at="2022-10-10T12:14:37 IST" name="valid" finished-at="2022-10-10T12:14:49 IST" duration-ms="11434" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- valid -->
        <test-method signature="validdata()[pri:1, instance:TestNG.login@2c1b194a]" started-at="2022-10-10T12:14:49 IST" name="validdata" finished-at="2022-10-10T12:14:53 IST" duration-ms="4319" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validdata -->
        <test-method signature="invalid()[pri:2, instance:TestNG.login@2c1b194a]" started-at="2022-10-10T12:14:53 IST" name="invalid" finished-at="2022-10-10T12:14:55 IST" duration-ms="2556" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalid -->
        <test-method signature="VerifyHomePageTitle()[pri:3, instance:TestNG.login@2c1b194a]" started-at="2022-10-10T12:14:55 IST" name="VerifyHomePageTitle" finished-at="2022-10-10T12:14:56 IST" duration-ms="49" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Rahul Shetty Academy login] but found [Rahul Shetty Academy]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Rahul Shetty Academy login] but found [Rahul Shetty Academy]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at TestNG.login.VerifyHomePageTitle(login.java:70)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyHomePageTitle -->
      </class> <!-- TestNG.login -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
